name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t tosini13/client -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true tosini13/client npm test
 
      - run: docker build -t tosini13/client ./client
      - run: docker build -t tosini13/nginx ./nginx
      - run: docker build -t tosini13/server ./server
      - run: docker build -t tosini13/worker ./worker
 
      - run: docker push tosini13/client
      - run: docker push tosini13/nginx
      - run: docker push tosini13/server
      - run: docker push tosini13/worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-course
          environment_name: Docker-course-env
          existing_bucket_name: elasticbeanstalk-us-east-1-951708948954
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip